name: Generate and Deploy Swagger UI

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

     
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn

      - name: Generate OpenAPI Schema
        run: |
          uvicorn app.main:create_app --factory --port 8000 &
          sleep 5  # Wait for the server to start
          curl -X GET "http://127.0.0.1:8000/openapi.json" -o openapi.json
          pkill uvicorn

      - name: Download Swagger UI
        run: |
          mkdir -p swagger-ui
          curl -LO https://github.com/swagger-api/swagger-ui/archive/refs/heads/master.zip
          unzip master.zip -d swagger-ui
          cp openapi.json swagger-ui/swagger-ui-master/dist/openapi.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui/swagger-ui-master/dist
